- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.vim:
    ~/.vimrc:
    ~/.tmux.conf:
    ~/.gitconfig:
    ~/.zshrc: 

- git:
    '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting':
        url: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
        description: 'zsh plugin: zsh-syntax-highlighting'
    '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions':
        url: 'https://github.com/zsh-users/zsh-autosuggestions'
        description: 'zsh plugin: zsh-autosuggestions'

- shell:
    -
        command: vim +PlugUpdate +qall &> /dev/null
        stdin: true
        stdout: true
        stderr: true
        description: Install vim plugins
    -
        command: git submodule sync --recursive
        description: sync submodules
    -
        command: git submodule update --init --recursive
        description: update submodules
