- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.vim:
    ~/.vimrc:
    ~/.tmux.conf:

- shell:
    -
        command: vim +PlugUpdate +qall &> /dev/null
        stdin: true
        stdout: true
        stderr: true
        description: Install vim plugins
    -
        command: git submodule sync --recursive
        description: sync submodules
    -
        command: git submodule update --init --recursive
        description: update submodules
